### PR TITLE
Added support for ValueOption

### PR DESCRIPTION
**Pull request by xperiandri**
I haven't found tests for `required` https://github.com/pimbrouwers/Validus/blob/42ad8cefdebf57a6b3ff4c8e642609e771c092d3/src/Validus/Validus.fs#L333
Do they exist?

### CODE REVIEW

**Comment by pimbrouwers** [comment]
Fantastic work, thank you so much! When I am back at home, hopefully this evening, I will review. 

It is entirely possible I forgot to add a test for required. Let me check when I get home.

**Comment by pimbrouwers** [comment]
I've trimmed all the extraneous whitespace from the master (I had no clue that setting was disabled on my personal computer, so stupid). 

Can you do a `git pull` from master to sync in all of those changes, then well merge this in.

Can you write the tests for required?

**Comment by xperiandri** [comment]
It is better if you make that, because I'm not good at it

**Comment by pimbrouwers** [comment]
Will do! No problem at all. I appreciate your time and energy on this very very much <3

**Pull request merged**
