### PR TITLE
Introduced Validator type for simplified functions declaration

### PR DESCRIPTION
**Pull request by xperiandri**
Also updated NuGet packages

### CODE REVIEW

**Comment by pimbrouwers** [comment]
What's up Andrii!! So nice to see all of this work.

Interestingly this project originally had the [exact type](https://github.com/pimbrouwers/Validus/blob/0c83a11b973983858ba2426ce6ac3c1f54fa0b94/src/Validus/Validus.fs#L7) you've created. Eventually I removed it because the tooling has trouble unfurling the inner definition when it's indirectly applied like it is here.

**Comment by xperiandri** [comment]
Do you have an example?

**Comment by xperiandri** [comment]
See what I did (draft, not completed)

**Comment by pimbrouwers** [comment]
> Do you have an example?

Beyond the link I provided, you could checkout an early early version of the nuget package and witness how it behaves in VS Code/Rider.

**Comment by pimbrouwers** [comment]
Being added to v4! Which is unfortunately, due to my error, currently in the main branch.

**Pull request closed without merging**
